name: canadian_house_prices
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas=2.2
  - altair=5.3
  - dash
  - dash-bootstrap-components
  - plotly
  - requests
  - vegafusion=1.6.9
  - vegafusion-python-embed=1.6.9
  - vl-convert-python>=1.3.0
  - pip=24.0
  - ipykernel  # Optional, for Jupyter support
  - tabulate  # Optional, for df.to_markdown()
  - lxml      
  - pytest
  - pip:
      - dash-vega-components